spring.datasource.url=jdbc:postgresql://dumbo.db.elephantsql.com/azfgdeud
spring.datasource.username=azfgdeud
spring.datasource.password=1iS6xoflEFjsGM0wWD6ieVL9ZBnvQkBv
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.baselineOnMigrate = true 
spring.flyway.validateOnMigrate = false 
