spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    #url: jdbc:postgresql://localhost:5432/postgres
    #username: postgres
    #password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
        format-sql: true
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
